import click

from create.al.cli import create_al

''' DO NOT EDIT THIS FILE
This is a generated file from template '/create/al/templates/group.py.tpl'
'''

@click.group()
def group(): pass

group.add_command(create_al)
